
// dummy data
export const courses = [
    {
        name: "Introduction to Programming",
        duration: 3,
        startDate: "2023-09-01",
        endDate: "2023-12-01",
        price: "300",
        registrationFees: "50",
        instructor: "Instructor 1",
        modules: 3,
        installments: 2,
    },
    {
        name: "Advanced JavaScript",
        duration: 2,
        startDate: "2023-10-01",
        endDate: "2023-12-01",
        price: "400",
        registrationFees: "60",
        instructor: "Instructor 2",
        modules: 4,
        installments: 1,
    },
    {
        name: "Data Science Basics",
        duration: 4,
        startDate: "2023-08-01",
        endDate: "2023-12-01",
        price: "500",
        registrationFees: "70",
        instructor: "Instructor 3",
        modules: 5,
        installments: 3,
    },
    {
        name: "Web Development Bootcamp",
        duration: 6,
        startDate: "2023-07-01",
        endDate: "2024-01-01",
        price: "600",
        registrationFees: "80",
        instructor: "Instructor 1",
        modules: 6,
        installments: 5,
    },
    {
        name: "Machine Learning",
        duration: 5,
        startDate: "2023-09-01",
        endDate: "2024-02-01",
        price: "700",
        registrationFees: "90",
        instructor: "Instructor 2",
        modules: 7,
        installments: 4,
    },
];
